# Generated by Django 5.0.13 on 2025-06-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='client_user_agent',
        ),
    ]
