# Generated by Django 5.0.13 on 2025-05-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='tenant_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='rolepermissionmapping',
            name='role_id',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator')], max_length=64),
        ),
        migrations.AlterField(
            model_name='rolepermissionmapping',
            name='tenant_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='tenant_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
