# Generated by Django 5.0.13 on 2025-06-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_alter_permission_tenant_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='client_user_agent',
        ),
        migrations.RemoveField(
            model_name='rolepermissionmapping',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='rolepermissionmapping',
            name='client_user_agent',
        ),
        migrations.RemoveField(
            model_name='token',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='token',
            name='client_user_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='client_user_agent',
        ),
    ]
