# Generated by Django 5.0.13 on 2025-05-29 13:32

import utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client_ip', models.CharField(default=None, max_length=128, null=True)),
                ('client_user_agent', models.CharField(default=None, max_length=128, null=True)),
                ('created_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('tenant_id', models.CharField(default=utils.functions.get_uuid, max_length=36, primary_key=True, serialize=False)),
                ('tenant_code', models.CharField(max_length=256)),
                ('tenant_name', models.CharField(max_length=256)),
                ('tenant_desc', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
    ]
