# Generated by Django 5.0.13 on 2025-06-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_desc',
        ),
    ]
