# Generated by Django 5.0.13 on 2025-06-05 07:04

import django.db.models.deletion
import utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_remove_tenant_tenant_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client_ip', models.CharField(default=None, max_length=128, null=True)),
                ('client_user_agent', models.CharField(default=None, max_length=128, null=True)),
                ('created_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('tenant_configuration_id', models.CharField(default=utils.functions.get_uuid, max_length=36, primary_key=True, serialize=False)),
                ('authentication_type', models.CharField(choices=[('TOKEN', 'Token'), ('JWT_TOKEN', 'JWT Token')], default='TOKEN', max_length=56)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'db_table': 'tenant_configurations',
            },
        ),
    ]
