# Generated by Django 5.0.13 on 2025-06-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_tenantconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='client_user_agent',
        ),
        migrations.RemoveField(
            model_name='tenantconfiguration',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='tenantconfiguration',
            name='client_user_agent',
        ),
    ]
