# Generated by Django 5.0.13 on 2025-06-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_remove_tenant_client_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='database_strategy',
            field=models.CharField(choices=[('SHARED', 'Shared DB'), ('SEPARATE', 'Separate DB')], default='SHARED', help_text='Defines whether the tenant uses a shared or separate database.', max_length=16),
        ),
    ]
