# Generated by Django 5.0.13 on 2025-05-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogs',
            name='tenant_id',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
