# Generated by Django 5.0.13 on 2025-06-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_alter_auditlogs_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='extra_details',
            field=models.JSONField(default=None, null=True),
        ),
    ]
