# Generated by Django 5.0.13 on 2025-06-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=20),
        ),
    ]
