# Generated by Django 5.0.13 on 2025-06-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_movement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='client_user_agent',
        ),
    ]
