# Generated by Django 5.0.13 on 2025-06-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stock_client_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='referance_number',
            new_name='reference_number',
        ),
    ]
