# Generated by Django 5.0.13 on 2025-06-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_category_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='category',
            name='client_user_agent',
        ),
    ]
