# Generated by Django 5.0.13 on 2025-06-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_product_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='product',
            name='client_user_agent',
        ),
    ]
